### ISSUE TITLE
Addons/fit

### ISSUE THREAD

**Issue by bilwit** [robert-harbison/xterm-for-react#2]
is there a way for the `fit` addon to work?

https://xtermjs.org/docs/api/addons/fit/

```javascript
  import React, { useState, useEffect } from 'react';
  import { XTerm } from 'xterm-for-react';
  import { FitAddon } from 'xterm-addon-fit';

  const Terminal = (props) => {
  const [input, setInput] = useState('');

  const xtermRef = React.useRef(null);
  const fitAddon = new FitAddon();

  useEffect(() => {
    // You can call any method in XTerm.js by using 'xterm xtermRef.current.terminal.[What you want to call]
    xtermRef.current.terminal.writeln('Hello, World!');
    fitAddon.fit();
  }, []);

  return (
    <div style={{ backgroundColor: 'red', width: '1000px' }}>
    <XTerm
      ref={xtermRef}
      addons={[fitAddon]}
      onData={(data) => {
        const code = data.charCodeAt(0);
        // If the user hits empty and there is `something` typed echo it.
        if (code === 13 && input.length > 0) {
          xtermRef.current.terminal.write(
            "\r\nYou typed: '" + input + "'\r\n",
          );
          xtermRef.current.terminal.write('echo> ');
          setInput('');
        } else if (code < 32 || code === 127) {
          // Disable control Keys such as arrow keys
          return;
        } else {
          // Add general key press characters to the terminal
          xtermRef.current.terminal.write(data);
          setInput((prev) => prev + data);
        }
      }}
    />
    </div>
  );
};

export default Terminal;
```

**Comment by dickenslian** [comment]
> is there a way for the `fit` addon to work?
> 
> https://xtermjs.org/docs/api/addons/fit/
> 
> ```js
>   import React, { useState, useEffect } from 'react';
>   import { XTerm } from 'xterm-for-react';
>   import { FitAddon } from 'xterm-addon-fit';
> 
>   const Terminal = (props) => {
>   const [input, setInput] = useState('');
> 
>   const xtermRef = React.useRef(null);
>   const fitAddon = new FitAddon();
> 
>   useEffect(() => {
>     // You can call any method in XTerm.js by using 'xterm xtermRef.current.terminal.[What you want to call]
>     xtermRef.current.terminal.writeln('Hello, World!');
>     fitAddon.fit();
>   }, []);
> 
>   return (
>     <div style={{ backgroundColor: 'red', width: '1000px' }}>
>     <XTerm
>       ref={xtermRef}
>       addons={[fitAddon]}
>       onData={(data) => {
>         const code = data.charCodeAt(0);
>         // If the user hits empty and there is `something` typed echo it.
>         if (code === 13 && input.length > 0) {
>           xtermRef.current.terminal.write(
>             "\r\nYou typed: '" + input + "'\r\n",
>           );
>           xtermRef.current.terminal.write('echo> ');
>           setInput('');
>         } else if (code < 32 || code === 127) {
>           // Disable control Keys such as arrow keys
>           return;
>         } else {
>           // Add general key press characters to the terminal
>           xtermRef.current.terminal.write(data);
>           setInput((prev) => prev + data);
>         }
>       }}
>     />
>     </div>
>   );
> };
> 
> export default Terminal;
> ```

I had the same issue. I solved it by adding className to XTerm component. Set the width & height in the corresponding class(myXterm). BTW, I'm using css modules here so the name of the class is a variable.
```js
<XTerm ref={this.xtermRef} addons={[this.fitAddon]} className={style.myXterm} />
```

**Comment by bilwit** [comment]
@dickenslian 

> I had the same issue. I solved it by adding className to XTerm component. Set the width & height in the corresponding class(myXterm). BTW, I'm using css modules here so the name of the class is a variable.
> 
> ```js
> <XTerm ref={this.xtermRef} addons={[this.fitAddon]} className={style.myXterm} />
> ```

This will indeed change the height/width of the element, however it will not change the amount of "columns" rendered by xterm which is what the addon looks to address. Changing the height/width via css while keeping the default amount of columns will just stretch the "image" of the terminal.

**Comment by dickenslian** [comment]
> @dickenslian
> 
> > I had the same issue. I solved it by adding className to XTerm component. Set the width & height in the corresponding class(myXterm). BTW, I'm using css modules here so the name of the class is a variable.
> > ```js
> > <XTerm ref={this.xtermRef} addons={[this.fitAddon]} className={style.myXterm} />
> > ```
> 
> This will indeed change the height/width of the element, however it will not change the amount of "columns" rendered by xterm which is what the addon looks to address. Changing the height/width via css while keeping the default amount of columns will just stretch the "image" of the terminal.

By saying "columns", you mean the amount of letters in a single line? I created a codesandbox. If I change the width of myXTerm class, the amount of letters in a single line did change.
[xtermjs with fit addon](https://codesandbox.io/s/happy-albattani-fl7mr?file=/src/App.js)

**Comment by bilwit** [comment]
@dickenslian
> By saying "columns", you mean the amount of letters in a single line? I created a codesandbox. If I change the width of myXTerm class, the amount of letters in a single line did change.
> [xtermjs with fit addon](https://codesandbox.io/s/happy-albattani-fl7mr?file=/src/App.js)

thank you very much, it seems that my `fitAddon.fit()` was being initialized at a weird point, moving it to a separate `useEffect` on mount allowed it to resize properly
