### ISSUE TITLE
React 17 Support

### ISSUE THREAD

**Issue by LordZardeck** [robert-harbison/xterm-for-react#5]
Not sure if this needs anything updated to support it, but NPM doesn't want to install this project with react 17. It would be nice if the project updated to support it.

**Comment by mcary** [comment]
@robert-harbison is PR #6 on-target to address this?  Thanks.

**Comment by robert-harbison** [comment]
PR #6  Has been merged.

**Comment by MHaz42** [comment]
Hi, 
Could it be possible to push the version of the package with the support of react17 on NPM please ?
Thanks in advance.
